# algorithms/pseudocode.py - Pseudocode definitions and highlight maps for AlgoFlow

PSEUDOCODE = {
    "Bubble": {
        "lines": [
            "for i = 0 to n-1:",
            "    for j = 0 to n-i-2:",
            "        if arr[j] > arr[j+1]:",
            "            swap(arr[j], arr[j+1])",
            "    // arr[n-i-1] is sorted",
        ],
        "highlight_map": {
            "compare": [2],
            "swap": [3],
            "sorted": [4],
            "done": [],
        },
    },
    "Selection": {
        "lines": [
            "for i = 0 to n-1:",
            "    min = i",
            "    for j = i+1 to n-1:",
            "        if arr[j] < arr[min]:",
            "            min = j",
            "    swap(arr[i], arr[min])",
            "    // arr[0..i] is sorted",
        ],
        "highlight_map": {
            "compare": [3],
            "swap": [5],
            "sorted": [6],
            "done": [],
        },
    },
    "Insertion": {
        "lines": [
            "for i = 1 to n-1:",
            "    key = arr[i]",
            "    j = i - 1",
            "    while j >= 0 and arr[j] > key:",
            "        arr[j+1] = arr[j]",
            "        j = j - 1",
            "    arr[j+1] = key",
        ],
        "highlight_map": {
            "compare": [3],
            "swap": [4],
            "sorted": [6],
            "done": [],
        },
    },
    "Merge": {
        "lines": [
            "mergeSort(arr, l, r):",
            "    if l < r:",
            "        mid = (l + r) / 2",
            "        mergeSort(arr, l, mid)",
            "        mergeSort(arr, mid+1, r)",
            "        merge(arr, l, mid, r)",
            "",
            "merge(left, right):",
            "    while both have elements:",
            "        compare left[i], right[j]",
            "        place smaller into arr[k]",
            "    copy remaining elements",
        ],
        "highlight_map": {
            "compare": [9],
            "set": [10, 11],
            "sorted": [5],
            "done": [],
        },
    },
    "Quick": {
        "lines": [
            "quickSort(arr, lo, hi):",
            "    if lo < hi:",
            "        p = partition(arr, lo, hi)",
            "        quickSort(arr, lo, p-1)",
            "        quickSort(arr, p+1, hi)",
            "",
            "partition(arr, lo, hi):",
            "    pivot = arr[hi]",
            "    i = lo - 1",
            "    for j = lo to hi-1:",
            "        if arr[j] <= pivot:",
            "            i++; swap(arr[i], arr[j])",
            "    swap(arr[i+1], arr[hi])",
        ],
        "highlight_map": {
            "pivot": [7],
            "compare": [10],
            "swap": [11],
            "sorted": [2],
            "done": [],
        },
    },
    "BFS": {
        "lines": [
            "function BFS(grid, start, end):",
            "  queue ← [start]",
            "  visited ← {start}",
            "  while queue is not empty:",
            "    node ← queue.dequeue()",
            "    if node = end: return path",
            "    for each neighbor of node:",
            "      if unvisited and not wall:",
            "        visited.add(neighbor)",
            "        queue.enqueue(neighbor)",
            "  return no path found",
        ],
        "highlight_map": {
            "frontier": [9],
            "visit": [4],
            "path": [5],
            "no_path": [10],
            "done": [],
        }
    },
    "DFS": {
        "lines": [
            "function DFS(grid, start, end):",
            "  stack ← [start]",
            "  visited ← {}",
            "  while stack is not empty:",
            "    node ← stack.pop()",
            "    if node in visited: continue",
            "    visited.add(node)",
            "    if node = end: return path",
            "    for each neighbor of node:",
            "      if unvisited and not wall:",
            "        stack.push(neighbor)",
            "  return no path found",
        ],
        "highlight_map": {
            "frontier": [10],
            "visit": [4, 6],
            "path": [7],
            "no_path": [11],
            "done": [],
        }
    },
    # --- Tree algorithms ---
    "BST Insert": {
        "lines": [
            "function insert(root, val):",
            "  if root is null:",
            "    return new Node(val)",
            "  if val < root.val:",
            "    root.left = insert(left, val)",
            "  else:",
            "    root.right = insert(right, val)",
            "  return root",
        ],
        "highlight_map": {
            "compare": [3, 5],
            "insert": [1, 2],
            "done": [],
        },
    },
    "BST Delete": {
        "lines": [
            "function delete(root, val):",
            "  find node with val",
            "  if leaf: remove node",
            "  if one child: replace with child",
            "  if two children:",
            "    find inorder successor",
            "    copy successor val to node",
            "    delete successor",
        ],
        "highlight_map": {
            "compare": [1],
            "highlight": [1],
            "successor": [5],
            "copy": [6],
            "remove": [2, 3, 7],
            "not_found": [1],
            "done": [],
        },
    },
    "BST Search": {
        "lines": [
            "function search(root, val):",
            "  if root is null: not found",
            "  if val = root.val: found!",
            "  if val < root.val:",
            "    return search(left, val)",
            "  else:",
            "    return search(right, val)",
        ],
        "highlight_map": {
            "compare": [3, 5],
            "found": [2],
            "not_found": [1],
            "done": [],
        },
    },
    "Inorder": {
        "lines": [
            "function inorder(node):",
            "  if node is null: return",
            "  inorder(node.left)",
            "  visit(node)",
            "  inorder(node.right)",
        ],
        "highlight_map": {
            "visit": [3],
            "done": [],
        },
    },
    "Preorder": {
        "lines": [
            "function preorder(node):",
            "  if node is null: return",
            "  visit(node)",
            "  preorder(node.left)",
            "  preorder(node.right)",
        ],
        "highlight_map": {
            "visit": [2],
            "done": [],
        },
    },
    "Postorder": {
        "lines": [
            "function postorder(node):",
            "  if node is null: return",
            "  postorder(node.left)",
            "  postorder(node.right)",
            "  visit(node)",
        ],
        "highlight_map": {
            "visit": [4],
            "done": [],
        },
    },
    "Level-order": {
        "lines": [
            "function levelorder(root):",
            "  queue ← [root]",
            "  while queue not empty:",
            "    node ← dequeue()",
            "    visit(node)",
            "    enqueue(node.left)",
            "    enqueue(node.right)",
        ],
        "highlight_map": {
            "visit": [4],
            "done": [],
        },
    },
    "Heap Insert": {
        "lines": [
            "function heapInsert(arr, val):",
            "  arr.append(val)",
            "  i ← len(arr) - 1",
            "  while i > 0:",
            "    parent ← (i-1) / 2",
            "    if arr[i] < arr[parent]:",
            "      swap(arr[i], arr[parent])",
            "      i ← parent",
            "    else: break",
        ],
        "highlight_map": {
            "compare": [5],
            "swap": [6],
            "done": [],
        },
    },
    "Heap Extract": {
        "lines": [
            "function extractMin(arr):",
            "  swap(arr[0], arr[last])",
            "  arr.pop()",
            "  i ← 0",
            "  while has children:",
            "    smallest ← min child",
            "    if arr[i] > arr[smallest]:",
            "      swap(arr[i], arr[smallest])",
            "      i ← smallest",
            "    else: break",
        ],
        "highlight_map": {
            "compare": [6],
            "swap": [1, 7],
            "error": [],
            "done": [],
        },
    },
}
